/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32f407xx_gpio.h"
#include "utility.h"
#include "usart.h"
#include "spi.h"

uint8_t gelen_data; //giden_data;

int main(void)
{
	// PA4 -> NSS Pin
	GPIO_Handle_t gpio_spi_nss_pin = {0};

	gpio_spi_nss_pin.pGPIOx = GPIOE;
	gpio_spi_nss_pin.gpio_pin_config.pin_number = GPIO_PIN_3;
	gpio_spi_nss_pin.gpio_pin_config.pin_mode = GPIO_MODE_OUT;
	gpio_spi_nss_pin.gpio_pin_config.pin_otype = GPIO_OTYPE_PP;
	gpio_spi_nss_pin.gpio_pin_config.pin_pu_pd = GPIO_PUPD_PU;

	gpio_init(&gpio_spi_nss_pin);

	//PA5 -> SCK Pin
	GPIO_Handle_t gpio_spi_sck_pin = {0};

	gpio_spi_sck_pin.pGPIOx = GPIOA;
	gpio_spi_sck_pin.gpio_pin_config.pin_number = GPIO_PIN_5;
	gpio_spi_sck_pin.gpio_pin_config.pin_mode = GPIO_MODE_ALTER;
	gpio_spi_sck_pin.gpio_pin_config.pin_alter_mode = GPIO_AF5;

	gpio_init(&gpio_spi_sck_pin);

	//PA6 -> MISO
	GPIO_Handle_t gpio_spi_miso_pin = {0};

	gpio_spi_miso_pin.pGPIOx = GPIOA;
	gpio_spi_miso_pin.gpio_pin_config.pin_number = GPIO_PIN_6;
	gpio_spi_miso_pin.gpio_pin_config.pin_mode = GPIO_MODE_ALTER;
	gpio_spi_miso_pin.gpio_pin_config.pin_alter_mode = GPIO_AF5;

	gpio_init(&gpio_spi_miso_pin);

	//PA7 -> MOSI_PIN
	GPIO_Handle_t gpio_spi_mosi_pin = {0};

	gpio_spi_mosi_pin.pGPIOx = GPIOA;
	gpio_spi_mosi_pin.gpio_pin_config.pin_number = GPIO_PIN_7;
	gpio_spi_mosi_pin.gpio_pin_config.pin_mode = GPIO_MODE_ALTER;
	gpio_spi_mosi_pin.gpio_pin_config.pin_otype = GPIO_OTYPE_PP;
	gpio_spi_mosi_pin.gpio_pin_config.pin_alter_mode = GPIO_AF5;

	gpio_init(&gpio_spi_mosi_pin);

	SPI_Handle_t spi_config = {0};
	spi_config.pSPIx = SPI1;
	spi_config.config.Mode = SPI_MODE_MASTER;
	spi_config.config.DataSize = SPI_DATASIZE_16BIT;
	spi_config.config.CLKPolarity = SPI_POLARITY_LOW;
	spi_config.config.CLKPhase = SPI_PHASE_1EDGE;
	spi_config.config.NSS = SPI_SSM_ENABLE;
	spi_config.config.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_8;
	spi_config.config.FirstBit = SPI_FIRSTBIT_MSB;

	spi_init(&spi_config);

	//char giden_data[30] = "Merhaba Dunya ";

	uint8_t giden_data = 0x0F;
	giden_data |= (1U << 7);

	gpio_spi_nss_pin.pGPIOx->ODR |= (1U << 3);

	//usart_disable(&uart_config, DISABLE_TX);
	while(1)
	{
		gpio_spi_nss_pin.pGPIOx->ODR &= ~(1U << 3);
		spi_write(&spi_config, &giden_data, 1);
		gelen_data = spi_read(&spi_config);
		gpio_spi_nss_pin.pGPIOx->ODR |= (1U << 3);
		delay(DELAY_SECOND(0.0001));
	}
}



